# Generated by Django 6.1 on 2026-08-10 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('condition_type', models.CharField(choices=[('FIRST_SESSION', 'Completed first session'), ('STREAK_DAYS', 'Reached a daily streak'), ('ABILITIES_COMPLETED', 'Completed N abilities'), ('JOURNEY_COMPLETED', 'Completed N journeys')], max_length=30)),
                ('condition_value', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='progress.badge')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
    ]
