# Generated by Django 6.1 on 2026-08-10 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='competencies/icons/')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Fallback order when the user has no personalized priority.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'competencies',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='abilities/icons/')),
                ('default_order', models.PositiveSmallIntegerField(default=0, help_text='Order of the ability inside its competency.')),
                ('is_active', models.BooleanField(default=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='abilities.competency')),
            ],
            options={
                'verbose_name_plural': 'abilities',
                'ordering': ['default_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('competency', 'name'), name='unique_ability_name_per_competency')],
            },
        ),
    ]
