# Generated by Django 4.2.30 on 2026-09-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='what_it_is',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competency',
            name='what_you_will_do',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competency',
            name='what_you_will_learn',
            field=models.JSONField(blank=True, default=list, help_text='List of strings describing what the user will learn'),
        ),
        migrations.AddField(
            model_name='competency',
            name='why_it_matters',
            field=models.TextField(blank=True),
        ),
    ]
