# Generated by Django 4.2.30 on 2026-09-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('MEDITATION', 'Meditation'), ('YOGA', 'Yoga'), ('ARTICLE', 'Article'), ('JOURNEY', 'Journey')], default='MEDITATION', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
