# Generated by Django 6.1 on 2026-08-10 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, help_text='Selected quick-reflection option.', max_length=255)),
                ('reflection_text', models.TextField(blank=True)),
                ('practice_answer', models.TextField(blank=True)),
                ('real_life_answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDailySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='Journey day (1–30).')),
                ('content_day', models.PositiveSmallIntegerField(default=1, help_text='Which AbilityDayContent day this session uses.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='AbilityDayContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(default=1, help_text='Content day within this ability (1 = first visit).')),
                ('title', models.CharField(max_length=200)),
                ('teaching_content', models.TextField(blank=True)),
                ('practice_content', models.TextField(blank=True)),
                ('real_life_plan', models.TextField(blank=True)),
                ('reflection_question', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_contents', to='abilities.ability')),
            ],
            options={
                'verbose_name_plural': 'ability day contents',
                'ordering': ['ability', 'day_number'],
            },
        ),
    ]
