# Generated by Django 6.1 on 2026-08-10 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abilities', '0001_initial'),
        ('journey', '0002_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdailysession',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='abilities.ability'),
        ),
        migrations.AddField(
            model_name='userdailysession',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='journey.userjourney'),
        ),
        migrations.AddField(
            model_name='userdailysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreflection',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='learning.userdailysession'),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_checkins', to='journey.userjourney'),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='abilitydaycontent',
            constraint=models.UniqueConstraint(fields=('ability', 'day_number'), name='unique_content_per_ability_day'),
        ),
        migrations.AddConstraint(
            model_name='userdailysession',
            constraint=models.UniqueConstraint(fields=('user', 'journey', 'ability', 'day_number'), name='unique_session_per_journey_day_ability'),
        ),
        migrations.AddConstraint(
            model_name='weeklycheckin',
            constraint=models.UniqueConstraint(fields=('user', 'journey', 'week_number'), name='unique_checkin_per_journey_week'),
        ),
    ]
