# Generated by Django 4.2.30 on 2026-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitydaycontent',
            name='key_concept',
            field=models.TextField(blank=True, help_text="The key concept text, e.g. 'Key Concept: Granularity...'"),
        ),
        migrations.AddField(
            model_name='abilitydaycontent',
            name='practice_options',
            field=models.JSONField(blank=True, default=list, help_text="List of strings for feeling chips, e.g. ['Calm', 'Annoyed']"),
        ),
    ]
