# Generated by Django 6.1 on 2026-08-10 01:50

import Apps.journey.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousOnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('journey_type', models.CharField(choices=[('AI_RECOMMENDED', 'AI recommended'), ('CUSTOM', 'Custom')], default='AI_RECOMMENDED', max_length=20)),
                ('expires_at', models.DateTimeField(default=Apps.journey.models.default_session_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('ai_priority', models.PositiveSmallIntegerField()),
                ('user_priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ai_priority'],
            },
        ),
        migrations.CreateModel(
            name='GrowthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('abilities_per_day', models.PositiveSmallIntegerField(default=1)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['abilities_per_day'],
            },
        ),
        migrations.CreateModel(
            name='GuidedJourneyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to='guided_journey/')),
                ('after_image', models.ImageField(upload_to='guided_journey/')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeTimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=True, help_text='Flexible options have no fixed window.')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('AI_RECOMMENDED', 'AI recommended'), ('CUSTOM', 'Custom')], default='AI_RECOMMENDED', max_length=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_day', models.PositiveSmallIntegerField(default=0)),
                ('total_days', models.PositiveSmallIntegerField(default=Apps.journey.models.default_total_days)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'user journeys',
                'ordering': ['-created_at'],
            },
        ),
    ]
