# Generated by Django 6.1 on 2026-08-10 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abilities', '0001_initial'),
        ('journey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousonboardingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='abilities.competency'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='journey.anonymousonboardingsession'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anonymousonboardingsession',
            name='growth_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journey.growthplan'),
        ),
        migrations.AddField(
            model_name='guidedjourneyimage',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_images', to='abilities.competency'),
        ),
        migrations.AddField(
            model_name='anonymousonboardingsession',
            name='practice_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journey.practicetimeoption'),
        ),
        migrations.AddField(
            model_name='userjourney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('session', 'competency'), name='unique_result_per_session_competency'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'competency'), name='unique_result_per_user_competency'),
        ),
        migrations.AddConstraint(
            model_name='userjourney',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'COMPLETED'), _negated=True), fields=('user',), name='unique_active_journey_per_user'),
        ),
    ]
